---
- name: Test Playbook
  hosts: all
  tasks:
  
  - name: Clone a github repository
     git:
       repo: https://github.com/yogitachourey123/clonetoansible.git
       dest: /home/hcligt
       clone: yes
       update: yes
	   
  - name: Run shell script
	  shell:
         "./demofile.sh"
		 
